---
- hosts: all
  tasks:
    - name: install node export
      include_role:
        name: cloudalchemy.node_exporter
      vars:
        node_exporter_version: "1.2.2"
        node_exporter_enabled_collectors: ["systemd","network_route",{textfile: {directory: "{{node_exporter_textfile_dir}}"}}]


### 前提是要安装下载  ansible-galaxy install cloudalchemy.node_exporter ## 多尝试几次下载